// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/form_data_content.proto

package org.mojo-lang.mojo.http;

/**
 * Protobuf type {@code mojo.http.FormDataContent}
 */
public final class FormDataContent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.http.FormDataContent)
    FormDataContentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FormDataContent.newBuilder() to construct.
  private FormDataContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FormDataContent() {
    transferEncoding_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FormDataContent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojo-lang.mojo.http.FormDataContent.class, org.mojo-lang.mojo.http.FormDataContent.Builder.class);
  }

  public interface DispositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mojo.http.FormDataContent.Disposition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string file_name = 3;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <code>string file_name = 3;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * Protobuf type {@code mojo.http.FormDataContent.Disposition}
   */
  public static final class Disposition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mojo.http.FormDataContent.Disposition)
      DispositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Disposition.newBuilder() to construct.
    private Disposition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Disposition() {
      value_ = "";
      name_ = "";
      fileName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Disposition();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_Disposition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_Disposition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojo-lang.mojo.http.FormDataContent.Disposition.class, org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 1;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object fileName_ = "";
    /**
     * <code>string file_name = 3;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <code>string file_name = 3;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, value_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fileName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, value_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fileName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mojo-lang.mojo.http.FormDataContent.Disposition)) {
        return super.equals(obj);
      }
      org.mojo-lang.mojo.http.FormDataContent.Disposition other = (org.mojo-lang.mojo.http.FormDataContent.Disposition) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojo-lang.mojo.http.FormDataContent.Disposition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mojo-lang.mojo.http.FormDataContent.Disposition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mojo.http.FormDataContent.Disposition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mojo.http.FormDataContent.Disposition)
        org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_Disposition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_Disposition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mojo-lang.mojo.http.FormDataContent.Disposition.class, org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder.class);
      }

      // Construct using org.mojo-lang.mojo.http.FormDataContent.Disposition.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        value_ = "";
        name_ = "";
        fileName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_Disposition_descriptor;
      }

      @java.lang.Override
      public org.mojo-lang.mojo.http.FormDataContent.Disposition getDefaultInstanceForType() {
        return org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance();
      }

      @java.lang.Override
      public org.mojo-lang.mojo.http.FormDataContent.Disposition build() {
        org.mojo-lang.mojo.http.FormDataContent.Disposition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mojo-lang.mojo.http.FormDataContent.Disposition buildPartial() {
        org.mojo-lang.mojo.http.FormDataContent.Disposition result = new org.mojo-lang.mojo.http.FormDataContent.Disposition(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.mojo-lang.mojo.http.FormDataContent.Disposition result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.value_ = value_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fileName_ = fileName_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mojo-lang.mojo.http.FormDataContent.Disposition) {
          return mergeFrom((org.mojo-lang.mojo.http.FormDataContent.Disposition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mojo-lang.mojo.http.FormDataContent.Disposition other) {
        if (other == org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                fileName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 1;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 1;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 1;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>string file_name = 3;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string file_name = 3;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string file_name = 3;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        fileName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        fileName_ = getDefaultInstance().getFileName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string file_name = 3;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        fileName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mojo.http.FormDataContent.Disposition)
    }

    // @@protoc_insertion_point(class_scope:mojo.http.FormDataContent.Disposition)
    private static final org.mojo-lang.mojo.http.FormDataContent.Disposition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mojo-lang.mojo.http.FormDataContent.Disposition();
    }

    public static org.mojo-lang.mojo.http.FormDataContent.Disposition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Disposition>
        PARSER = new com.google.protobuf.AbstractParser<Disposition>() {
      @java.lang.Override
      public Disposition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Disposition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Disposition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.http.FormDataContent.Disposition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int DISPOSITION_FIELD_NUMBER = 1;
  private org.mojo-lang.mojo.http.FormDataContent.Disposition disposition_;
  /**
   * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
   * @return Whether the disposition field is set.
   */
  @java.lang.Override
  public boolean hasDisposition() {
    return disposition_ != null;
  }
  /**
   * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
   * @return The disposition.
   */
  @java.lang.Override
  public org.mojo-lang.mojo.http.FormDataContent.Disposition getDisposition() {
    return disposition_ == null ? org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance() : disposition_;
  }
  /**
   * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder getDispositionOrBuilder() {
    return disposition_ == null ? org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance() : disposition_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private org.mojolang.mojo.core.MediaType type_;
  /**
   * <code>.mojo.core.MediaType type = 2;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return type_ != null;
  }
  /**
   * <code>.mojo.core.MediaType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.MediaType getType() {
    return type_ == null ? org.mojolang.mojo.core.MediaType.getDefaultInstance() : type_;
  }
  /**
   * <code>.mojo.core.MediaType type = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.MediaTypeOrBuilder getTypeOrBuilder() {
    return type_ == null ? org.mojolang.mojo.core.MediaType.getDefaultInstance() : type_;
  }

  public static final int TRANSFER_ENCODING_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transferEncoding_ = "";
  /**
   * <code>string transfer_encoding = 3;</code>
   * @return The transferEncoding.
   */
  @java.lang.Override
  public java.lang.String getTransferEncoding() {
    java.lang.Object ref = transferEncoding_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transferEncoding_ = s;
      return s;
    }
  }
  /**
   * <code>string transfer_encoding = 3;</code>
   * @return The bytes for transferEncoding.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransferEncodingBytes() {
    java.lang.Object ref = transferEncoding_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transferEncoding_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADERS_FIELD_NUMBER = 4;
  private org.mojo-lang.mojo.http.Headers headers_;
  /**
   * <code>.mojo.http.Headers headers = 4;</code>
   * @return Whether the headers field is set.
   */
  @java.lang.Override
  public boolean hasHeaders() {
    return headers_ != null;
  }
  /**
   * <code>.mojo.http.Headers headers = 4;</code>
   * @return The headers.
   */
  @java.lang.Override
  public org.mojo-lang.mojo.http.Headers getHeaders() {
    return headers_ == null ? org.mojo-lang.mojo.http.Headers.getDefaultInstance() : headers_;
  }
  /**
   * <code>.mojo.http.Headers headers = 4;</code>
   */
  @java.lang.Override
  public org.mojo-lang.mojo.http.HeadersOrBuilder getHeadersOrBuilder() {
    return headers_ == null ? org.mojo-lang.mojo.http.Headers.getDefaultInstance() : headers_;
  }

  public static final int VALUE_FIELD_NUMBER = 5;
  private org.mojolang.mojo.core.Value value_;
  /**
   * <code>.mojo.core.Value value = 5;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <code>.mojo.core.Value value = 5;</code>
   * @return The value.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Value getValue() {
    return value_ == null ? org.mojolang.mojo.core.Value.getDefaultInstance() : value_;
  }
  /**
   * <code>.mojo.core.Value value = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.ValueOrBuilder getValueOrBuilder() {
    return value_ == null ? org.mojolang.mojo.core.Value.getDefaultInstance() : value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (disposition_ != null) {
      output.writeMessage(1, getDisposition());
    }
    if (type_ != null) {
      output.writeMessage(2, getType());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transferEncoding_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, transferEncoding_);
    }
    if (headers_ != null) {
      output.writeMessage(4, getHeaders());
    }
    if (value_ != null) {
      output.writeMessage(5, getValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (disposition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDisposition());
    }
    if (type_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getType());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transferEncoding_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, transferEncoding_);
    }
    if (headers_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getHeaders());
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojo-lang.mojo.http.FormDataContent)) {
      return super.equals(obj);
    }
    org.mojo-lang.mojo.http.FormDataContent other = (org.mojo-lang.mojo.http.FormDataContent) obj;

    if (hasDisposition() != other.hasDisposition()) return false;
    if (hasDisposition()) {
      if (!getDisposition()
          .equals(other.getDisposition())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (!getTransferEncoding()
        .equals(other.getTransferEncoding())) return false;
    if (hasHeaders() != other.hasHeaders()) return false;
    if (hasHeaders()) {
      if (!getHeaders()
          .equals(other.getHeaders())) return false;
    }
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDisposition()) {
      hash = (37 * hash) + DISPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getDisposition().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    hash = (37 * hash) + TRANSFER_ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + getTransferEncoding().hashCode();
    if (hasHeaders()) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeaders().hashCode();
    }
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.http.FormDataContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojo-lang.mojo.http.FormDataContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.http.FormDataContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.http.FormDataContent)
      org.mojo-lang.mojo.http.FormDataContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojo-lang.mojo.http.FormDataContent.class, org.mojo-lang.mojo.http.FormDataContent.Builder.class);
    }

    // Construct using org.mojo-lang.mojo.http.FormDataContent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      disposition_ = null;
      if (dispositionBuilder_ != null) {
        dispositionBuilder_.dispose();
        dispositionBuilder_ = null;
      }
      type_ = null;
      if (typeBuilder_ != null) {
        typeBuilder_.dispose();
        typeBuilder_ = null;
      }
      transferEncoding_ = "";
      headers_ = null;
      if (headersBuilder_ != null) {
        headersBuilder_.dispose();
        headersBuilder_ = null;
      }
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojo-lang.mojo.http.FormDataContentProto.internal_static_mojo_http_FormDataContent_descriptor;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.http.FormDataContent getDefaultInstanceForType() {
      return org.mojo-lang.mojo.http.FormDataContent.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojo-lang.mojo.http.FormDataContent build() {
      org.mojo-lang.mojo.http.FormDataContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.http.FormDataContent buildPartial() {
      org.mojo-lang.mojo.http.FormDataContent result = new org.mojo-lang.mojo.http.FormDataContent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.mojo-lang.mojo.http.FormDataContent result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.disposition_ = dispositionBuilder_ == null
            ? disposition_
            : dispositionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = typeBuilder_ == null
            ? type_
            : typeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.transferEncoding_ = transferEncoding_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.headers_ = headersBuilder_ == null
            ? headers_
            : headersBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojo-lang.mojo.http.FormDataContent) {
        return mergeFrom((org.mojo-lang.mojo.http.FormDataContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojo-lang.mojo.http.FormDataContent other) {
      if (other == org.mojo-lang.mojo.http.FormDataContent.getDefaultInstance()) return this;
      if (other.hasDisposition()) {
        mergeDisposition(other.getDisposition());
      }
      if (other.hasType()) {
        mergeType(other.getType());
      }
      if (!other.getTransferEncoding().isEmpty()) {
        transferEncoding_ = other.transferEncoding_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasHeaders()) {
        mergeHeaders(other.getHeaders());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getDispositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTypeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              transferEncoding_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getHeadersFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.mojo-lang.mojo.http.FormDataContent.Disposition disposition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.http.FormDataContent.Disposition, org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder, org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder> dispositionBuilder_;
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     * @return Whether the disposition field is set.
     */
    public boolean hasDisposition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     * @return The disposition.
     */
    public org.mojo-lang.mojo.http.FormDataContent.Disposition getDisposition() {
      if (dispositionBuilder_ == null) {
        return disposition_ == null ? org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance() : disposition_;
      } else {
        return dispositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public Builder setDisposition(org.mojo-lang.mojo.http.FormDataContent.Disposition value) {
      if (dispositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        disposition_ = value;
      } else {
        dispositionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public Builder setDisposition(
        org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder builderForValue) {
      if (dispositionBuilder_ == null) {
        disposition_ = builderForValue.build();
      } else {
        dispositionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public Builder mergeDisposition(org.mojo-lang.mojo.http.FormDataContent.Disposition value) {
      if (dispositionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          disposition_ != null &&
          disposition_ != org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance()) {
          getDispositionBuilder().mergeFrom(value);
        } else {
          disposition_ = value;
        }
      } else {
        dispositionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public Builder clearDisposition() {
      bitField0_ = (bitField0_ & ~0x00000001);
      disposition_ = null;
      if (dispositionBuilder_ != null) {
        dispositionBuilder_.dispose();
        dispositionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder getDispositionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getDispositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    public org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder getDispositionOrBuilder() {
      if (dispositionBuilder_ != null) {
        return dispositionBuilder_.getMessageOrBuilder();
      } else {
        return disposition_ == null ?
            org.mojo-lang.mojo.http.FormDataContent.Disposition.getDefaultInstance() : disposition_;
      }
    }
    /**
     * <code>.mojo.http.FormDataContent.Disposition disposition = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.http.FormDataContent.Disposition, org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder, org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder> 
        getDispositionFieldBuilder() {
      if (dispositionBuilder_ == null) {
        dispositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojo-lang.mojo.http.FormDataContent.Disposition, org.mojo-lang.mojo.http.FormDataContent.Disposition.Builder, org.mojo-lang.mojo.http.FormDataContent.DispositionOrBuilder>(
                getDisposition(),
                getParentForChildren(),
                isClean());
        disposition_ = null;
      }
      return dispositionBuilder_;
    }

    private org.mojolang.mojo.core.MediaType type_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.MediaType, org.mojolang.mojo.core.MediaType.Builder, org.mojolang.mojo.core.MediaTypeOrBuilder> typeBuilder_;
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     * @return The type.
     */
    public org.mojolang.mojo.core.MediaType getType() {
      if (typeBuilder_ == null) {
        return type_ == null ? org.mojolang.mojo.core.MediaType.getDefaultInstance() : type_;
      } else {
        return typeBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public Builder setType(org.mojolang.mojo.core.MediaType value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
      } else {
        typeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public Builder setType(
        org.mojolang.mojo.core.MediaType.Builder builderForValue) {
      if (typeBuilder_ == null) {
        type_ = builderForValue.build();
      } else {
        typeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public Builder mergeType(org.mojolang.mojo.core.MediaType value) {
      if (typeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          type_ != null &&
          type_ != org.mojolang.mojo.core.MediaType.getDefaultInstance()) {
          getTypeBuilder().mergeFrom(value);
        } else {
          type_ = value;
        }
      } else {
        typeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = null;
      if (typeBuilder_ != null) {
        typeBuilder_.dispose();
        typeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public org.mojolang.mojo.core.MediaType.Builder getTypeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTypeFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    public org.mojolang.mojo.core.MediaTypeOrBuilder getTypeOrBuilder() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilder();
      } else {
        return type_ == null ?
            org.mojolang.mojo.core.MediaType.getDefaultInstance() : type_;
      }
    }
    /**
     * <code>.mojo.core.MediaType type = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.MediaType, org.mojolang.mojo.core.MediaType.Builder, org.mojolang.mojo.core.MediaTypeOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.MediaType, org.mojolang.mojo.core.MediaType.Builder, org.mojolang.mojo.core.MediaTypeOrBuilder>(
                getType(),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }

    private java.lang.Object transferEncoding_ = "";
    /**
     * <code>string transfer_encoding = 3;</code>
     * @return The transferEncoding.
     */
    public java.lang.String getTransferEncoding() {
      java.lang.Object ref = transferEncoding_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transferEncoding_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transfer_encoding = 3;</code>
     * @return The bytes for transferEncoding.
     */
    public com.google.protobuf.ByteString
        getTransferEncodingBytes() {
      java.lang.Object ref = transferEncoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transferEncoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transfer_encoding = 3;</code>
     * @param value The transferEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setTransferEncoding(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transferEncoding_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string transfer_encoding = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransferEncoding() {
      transferEncoding_ = getDefaultInstance().getTransferEncoding();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string transfer_encoding = 3;</code>
     * @param value The bytes for transferEncoding to set.
     * @return This builder for chaining.
     */
    public Builder setTransferEncodingBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transferEncoding_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private org.mojo-lang.mojo.http.Headers headers_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.http.Headers, org.mojo-lang.mojo.http.Headers.Builder, org.mojo-lang.mojo.http.HeadersOrBuilder> headersBuilder_;
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     * @return Whether the headers field is set.
     */
    public boolean hasHeaders() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     * @return The headers.
     */
    public org.mojo-lang.mojo.http.Headers getHeaders() {
      if (headersBuilder_ == null) {
        return headers_ == null ? org.mojo-lang.mojo.http.Headers.getDefaultInstance() : headers_;
      } else {
        return headersBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public Builder setHeaders(org.mojo-lang.mojo.http.Headers value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        headers_ = value;
      } else {
        headersBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public Builder setHeaders(
        org.mojo-lang.mojo.http.Headers.Builder builderForValue) {
      if (headersBuilder_ == null) {
        headers_ = builderForValue.build();
      } else {
        headersBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public Builder mergeHeaders(org.mojo-lang.mojo.http.Headers value) {
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          headers_ != null &&
          headers_ != org.mojo-lang.mojo.http.Headers.getDefaultInstance()) {
          getHeadersBuilder().mergeFrom(value);
        } else {
          headers_ = value;
        }
      } else {
        headersBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public Builder clearHeaders() {
      bitField0_ = (bitField0_ & ~0x00000008);
      headers_ = null;
      if (headersBuilder_ != null) {
        headersBuilder_.dispose();
        headersBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public org.mojo-lang.mojo.http.Headers.Builder getHeadersBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getHeadersFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    public org.mojo-lang.mojo.http.HeadersOrBuilder getHeadersOrBuilder() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilder();
      } else {
        return headers_ == null ?
            org.mojo-lang.mojo.http.Headers.getDefaultInstance() : headers_;
      }
    }
    /**
     * <code>.mojo.http.Headers headers = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojo-lang.mojo.http.Headers, org.mojo-lang.mojo.http.Headers.Builder, org.mojo-lang.mojo.http.HeadersOrBuilder> 
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojo-lang.mojo.http.Headers, org.mojo-lang.mojo.http.Headers.Builder, org.mojo-lang.mojo.http.HeadersOrBuilder>(
                getHeaders(),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }

    private org.mojolang.mojo.core.Value value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Value, org.mojolang.mojo.core.Value.Builder, org.mojolang.mojo.core.ValueOrBuilder> valueBuilder_;
    /**
     * <code>.mojo.core.Value value = 5;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     * @return The value.
     */
    public org.mojolang.mojo.core.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? org.mojolang.mojo.core.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public Builder setValue(org.mojolang.mojo.core.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public Builder setValue(
        org.mojolang.mojo.core.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public Builder mergeValue(org.mojolang.mojo.core.Value value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          value_ != null &&
          value_ != org.mojolang.mojo.core.Value.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public org.mojolang.mojo.core.Value.Builder getValueBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    public org.mojolang.mojo.core.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            org.mojolang.mojo.core.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <code>.mojo.core.Value value = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Value, org.mojolang.mojo.core.Value.Builder, org.mojolang.mojo.core.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Value, org.mojolang.mojo.core.Value.Builder, org.mojolang.mojo.core.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.http.FormDataContent)
  }

  // @@protoc_insertion_point(class_scope:mojo.http.FormDataContent)
  private static final org.mojo-lang.mojo.http.FormDataContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojo-lang.mojo.http.FormDataContent();
  }

  public static org.mojo-lang.mojo.http.FormDataContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FormDataContent>
      PARSER = new com.google.protobuf.AbstractParser<FormDataContent>() {
    @java.lang.Override
    public FormDataContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FormDataContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FormDataContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojo-lang.mojo.http.FormDataContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

