// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/header.proto

package org.mojo-lang.mojo.http;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_http_Header_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_http_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mojo/http/header.proto\022\tmojo.http\"%\n\006H" +
      "eader\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\tBY\n\027or" +
      "g.mojo-lang.mojo.httpB\013HeaderProtoP\001Z/gi" +
      "thub.com/mojo-lang/http/go/pkg/mojo/http" +
      ";httpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_http_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_http_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_http_Header_descriptor,
        new java.lang.String[] { "Name", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
