// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/multipart_form_data.proto

package org.mojo-lang.mojo.http;

public interface MultipartFormDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.http.MultipartFormData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string boundary = 1;</code>
   * @return The boundary.
   */
  java.lang.String getBoundary();
  /**
   * <code>string boundary = 1;</code>
   * @return The bytes for boundary.
   */
  com.google.protobuf.ByteString
      getBoundaryBytes();

  /**
   * <code>repeated .mojo.http.FormDataContent parts = 2;</code>
   */
  java.util.List<org.mojo-lang.mojo.http.FormDataContent> 
      getPartsList();
  /**
   * <code>repeated .mojo.http.FormDataContent parts = 2;</code>
   */
  org.mojo-lang.mojo.http.FormDataContent getParts(int index);
  /**
   * <code>repeated .mojo.http.FormDataContent parts = 2;</code>
   */
  int getPartsCount();
  /**
   * <code>repeated .mojo.http.FormDataContent parts = 2;</code>
   */
  java.util.List<? extends org.mojo-lang.mojo.http.FormDataContentOrBuilder> 
      getPartsOrBuilderList();
  /**
   * <code>repeated .mojo.http.FormDataContent parts = 2;</code>
   */
  org.mojo-lang.mojo.http.FormDataContentOrBuilder getPartsOrBuilder(
      int index);
}
