// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/request.proto

package org.mojo-lang.mojo.http;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_http_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_http_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/http/request.proto\022\tmojo.http\032\023mo" +
      "jo/core/url.proto\032\025mojo/core/value.proto" +
      "\032\027mojo/http/headers.proto\032\026mojo/http/met" +
      "hod.proto\032\027mojo/http/version.proto\"\263\001\n\007R" +
      "equest\022!\n\006method\030\001 \001(\0162\021.mojo.http.Metho" +
      "d\022\033\n\003url\030\002 \001(\0132\016.mojo.core.Url\022#\n\007versio" +
      "n\030\003 \001(\0132\022.mojo.http.Version\022#\n\007headers\030\004" +
      " \001(\0132\022.mojo.http.Headers\022\036\n\004body\030\005 \001(\0132\020" +
      ".mojo.core.ValueBZ\n\027org.mojo-lang.mojo.h" +
      "ttpB\014RequestProtoP\001Z/github.com/mojo-lan" +
      "g/http/go/pkg/mojo/http;httpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.UrlProto.getDescriptor(),
          org.mojolang.mojo.core.ValueProto.getDescriptor(),
          org.mojo-lang.mojo.http.HeadersProto.getDescriptor(),
          org.mojo-lang.mojo.http.MethodProto.getDescriptor(),
          org.mojo-lang.mojo.http.VersionProto.getDescriptor(),
        });
    internal_static_mojo_http_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_http_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_http_Request_descriptor,
        new java.lang.String[] { "Method", "Url", "Version", "Headers", "Body", });
    org.mojolang.mojo.core.UrlProto.getDescriptor();
    org.mojolang.mojo.core.ValueProto.getDescriptor();
    org.mojo-lang.mojo.http.HeadersProto.getDescriptor();
    org.mojo-lang.mojo.http.MethodProto.getDescriptor();
    org.mojo-lang.mojo.http.VersionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
