// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/router.proto

package org.mojo-lang.mojo.http;

public interface RouterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.http.Router)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   * @return Whether the path field is set.
   */
  boolean hasPath();
  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   * @return The path.
   */
  org.mojolang.mojo.core.TemplateString getPath();
  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   */
  org.mojolang.mojo.core.TemplateStringOrBuilder getPathOrBuilder();

  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  java.util.List<org.mojo-lang.mojo.http.TemplateHeader> 
      getHeadersList();
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  org.mojo-lang.mojo.http.TemplateHeader getHeaders(int index);
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  int getHeadersCount();
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  java.util.List<? extends org.mojo-lang.mojo.http.TemplateHeaderOrBuilder> 
      getHeadersOrBuilderList();
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  org.mojo-lang.mojo.http.TemplateHeaderOrBuilder getHeadersOrBuilder(
      int index);

  /**
   * <code>.mojo.http.Method method = 10;</code>
   * @return The enum numeric value on the wire for method.
   */
  int getMethodValue();
  /**
   * <code>.mojo.http.Method method = 10;</code>
   * @return The method.
   */
  org.mojo-lang.mojo.http.Method getMethod();
}
