// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/text.proto

package org.mojo-lang.mojo.http;

public interface TextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.http.Text)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
