// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/version.proto

package org.mojo-lang.mojo.http;

public final class VersionProto {
  private VersionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_http_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_http_Version_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027mojo/http/version.proto\022\tmojo.http\"\'\n\007" +
      "Version\022\r\n\005major\030\001 \001(\005\022\r\n\005minor\030\002 \001(\005BZ\n" +
      "\027org.mojo-lang.mojo.httpB\014VersionProtoP\001" +
      "Z/github.com/mojo-lang/http/go/pkg/mojo/" +
      "http;httpb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_http_Version_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_http_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_http_Version_descriptor,
        new java.lang.String[] { "Major", "Minor", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
