// Code generated by mojo. DO NOT EDIT.
// Rerunning mojo will overwrite this file.
//
// Copyright 2021 Mojo-lang.org
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package http

import (
	"strconv"
)

var MethodNames = map[int32]string{
	0: "UNSEPECIFIED",
	1: "GET",
	2: "POST",
	3: "PUT",
	4: "PATCH",
	5: "DELETE",
	6: "OPTIONS",
	7: "HEAD",
	8: "TRACE",
	9: "CONNECT",
}

var MethodValues = map[string]Method{
	"UNSEPECIFIED": Method_METHOD_UNSEPECIFIED,
	"GET":          Method_METHOD_GET,
	"POST":         Method_METHOD_POST,
	"PUT":          Method_METHOD_PUT,
	"PATCH":        Method_METHOD_PATCH,
	"DELETE":       Method_METHOD_DELETE,
	"OPTIONS":      Method_METHOD_OPTIONS,
	"HEAD":         Method_METHOD_HEAD,
	"TRACE":        Method_METHOD_TRACE,
	"CONNECT":      Method_METHOD_CONNECT,
}

func (x Method) Format() string {
	s, ok := MethodNames[int32(x)]
	if ok {
		return s
	}
	if int(x) == 0 {
		return "unspecified"
	}
	return strconv.Itoa(int(x))
}

func (x *Method) Parse(value string) error {
	if x != nil {
		s, ok := MethodValues[value]
		if ok {
			*x = s
		} else {
			*x = Method_METHOD_UNSEPECIFIED
		}
	} else {
		*x = Method_METHOD_UNSEPECIFIED
	}
	return nil
}
